### PR TITLE
Refactoring UI stuff

### PR DESCRIPTION
**Pull request by jakebromberg**
Simplified InfoDetailViewController
Refactored auto layout constraints for the NowPlayingViewController to make it adaptable for all iPhone sizes

### CODE REVIEW

**Comment by dvdokkum** [comment]
+1

**Comment by dvdokkum** [comment]
Just ran this in simulator.... looks like with the Album Art much bigger the Track Info is getting slightly squished on smaller screens (iPhone SE)
screen shot 2017-11-14 at 8 07 45 pm

**Comment by jakebromberg** [comment]
Will fix now and post PR with screenshot

**Comment by jakebromberg** [comment]
Sorry for the delay on fixing this. I'm making sure that the layout looks
better than garbage on all devices (that aren't iPads)

**Pull request merged**
